var CONFIG = CONFIG || {};

CONFIG.VISIBLE_MIN_PEOPLE_CNT = 3;
CONFIG.VISIBLE_MAX_PEOPLE_CNT = 30;
CONFIG.PEOPLE_DEAD_SECOND = 6;
CONFIG.PEOPLE_EAT_FOOD_RATE = 3;
CONFIG.TAX_PER_PEOPLE = 4;
CONFIG.DEBUG_ADD_AMOUNT = 0;
CONFIG.MAX_AMOUNT = 300;
CONFIG.CYCLE_SECOND = 60 * 1 * 1.5;
CONFIG.CYCLE_BACKGROUND_SECOND = 60 * 1 * 60 * 2;
CONFIG.ITEM_MONEY_AMOUNT = 30;
CONFIG.ITEM_FOOD_AMOUNT = 30;
CONFIG.ITEM_DOKI_AMOUNT = 1;
CONFIG.ITEM_ILL_AMOUNT = 5;