var res = {
    Map_Nature_png : "res/map_nature.png",
    Map_Grand_png : "res/map_grand.png",
    Map_Target_Ok_png : "res/map_target_ok.png",
    Map_Target_Ng_png : "res/map_target_ng.png",
    Header150_png : "res/header150.png",
    Header150_over_png : "res/header150_on.png",
    Setting_Window_png : "res/menuShop.png",
    Setting_Menu_png : "res/menuSetting.png",
    Item_Window_png : "res/item_001.png",
    Setting_Button_Scale_001_png : "res/scale_plus_button.png",
    Setting_Button_Scale_002_png : "res/scale_minus_button.png",
    Animal_001_png : "res/chara004.png",
    Animal_002_png : "res/chara005.png",
    Animal_003_png : "res/chara006.png",
    Message_png : "res/message.png",
    Ok_Button_png : "res/ok_button.png",
    Setting_Menu_Button_001_png : "res/setting_menu_button_001.png",
    Setting_Menu_Button_002_png : "res/setting_menu_button_002.png",
    Setting_Menu_Button_003_png : "res/setting_menu_button_003.png",
    Item_Null_Button_png : "res/item_null.png",
    Item_None_Button_png : "res/item_null.png",
    Reset_png : "res/reset.png",
    Message1_png : "res/message_board.png",
    Message_Ok_Button_png : "res/message_ok_button.png",
    Message_Ok_Button2_png : "res/message_ok_button.png",
    Message_Cancel_Button_png : "res/message_cancel_button.png",
    Data_Reset_Button_png : "res/data_reset.png",
    Positioning_png : "res/positioning.png",
    Item_Select_png : "res/item_select.png",
    Build_Ok_Button : "res/ok_button.png",
    Build_Rotate_Button : "res/rotate_button.png",
    Build_Ng_Button : "res/ng_button.png",
    Item_No_Money_png : "res/item_no_money.png",
    Tutorial_Page_001 : "res/tutorial_001.png",
    Tutorial_Page_002 : "res/tutorial_002.png",
    Tutorial_Page_003 : "res/tutorial_003.png",
    Tutorial_Page_004 : "res/tutorial_004.png",
    Tutorial_Page_005 : "res/tutorial_005.png",
    Tutorial_Page_006 : "res/tutorial_006.png",
    Sound_On_Button_png : "res/sound_on_button.png",
    Sound_Off_Button_png : "res/sound_off_button.png",
    Tutorial_Left_Button : "res/button_tutorial_left.png",
    Tutorial_Right_Button : "res/button_tutorial_right.png",
    Tutorial_Close_Button : "res/button_tutorial_close.png",
    BGM_001_mp3 : "res/bgm_normal.mp3",
    SE_001_mp3 : "res/se_001.mp3",
    SE_002_mp3 : "res/se_002.mp3",
    Info_png : "res/info.fw.png",
    Himiko_Message_png : "res/himiko_message.png",
    Himiko_png : "res/himiko.png",
    Building_Button_png : "res/building_button.png",
    Building_Button_On_png : "res/building_button_on.png",
    Setting_Button_png : "res/setting_button.png",
    Setting_Button_On_png : "res/setting_button_on.png",
    Info_Button_png : "res/info_button.png",
    Info_Button_On_png : "res/info_button_on.png",
    Info_Ok_Button_png : "res/ok_review_button.png",
    Info_Ok_Button_On_png : "res/ok_review_button_on.png",
    Food_Base_Sprite_png : "res/f_i001_base.png",
    Himiko_png : "res/himiko_big.png",
    Credit_png : "res/credit.png",
    Button_Credit_png : "res/button_credit.png",
    Button_Close_png : "res/button_close.png",
    Population_Button_png : "res/population_button.png",
    Population_Button_On_png : "res/population_button_on.png",
    Effect_Enemy_png : "res/flame3.png",
    Effect_Money_png : "res/pipo-btleffect142.png",
    Effect_Hart_png : "res/pipo-btleffect019.png",
    Unuse_Sprite_png : "res/population_ng_button.png",
    Attack_Window_png : "res/attack_window.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}