var res = {
    Map_Nature_png : "res/map_nature.png",
    Map_Grand_png : "res/map_grand.png",
    Map_Target_Ok_png : "res/map_target_ok.png",
    Map_Target_Ng_png : "res/map_target_ng.png",
    Header150_png : "res/header150.png",
    Header150_over_png : "res/header150_on.png",

    Item_Window_png : "res/item_001.png",
    Animal_001_png : "res/chara004.png",
    Animal_002_png : "res/chara005.png",
    Animal_003_png : "res/chara006.png",
    Enemy_001_png : "res/enemy003.png",

    UI_Reward_Line_png : "res/reward_line.png",
    Icon_Cleared_Reward_png : "res/icon_cleared_reward.png",
    
    Item_Null_Button_png : "res/item_null.png",
    Item_None_Button_png : "res/item_null.png",
    Item_Select_png : "res/item_select.png",
    Item_No_Money_png : "res/item_no_money.png",

    Tutorial_Page_001 : "res/tutorial_001.png",
    Tutorial_Page_002 : "res/tutorial_002.png",
    Tutorial_Page_003 : "res/tutorial_003.png",
    Tutorial_Page_004 : "res/tutorial_004.png",
    Tutorial_Page_005 : "res/tutorial_005.png",
    Tutorial_Page_006 : "res/tutorial_006.png",

    Button_Setting_Menu_001_png : "res/button_setting_menu_001.png",
    Button_Setting_Menu_002_png : "res/button_setting_menu_002.png",
    Button_Setting_Menu_003_png : "res/button_setting_menu_003.png",
    Button_Setting_Menu_001_On_png : "res/button_setting_menu_001_on.png",
    Button_Setting_Menu_002_On_png : "res/button_setting_menu_002_on.png",
    Button_Setting_Menu_003_On_png : "res/button_setting_menu_003_on.png",
    Button_Header_Reward_png : "res/button_header_reward.png",
    Button_Data_Reset_png : "res/button_data_reset.png",
    Button_Ok_png : "res/button_ok.png",
    Button_Ng_png : "res/button_ng.png",
    Button_Ok_On_png : "res/button_ok_on.png",
    Button_Ng_On_png : "res/button_ng_on.png",

    Build_Ok_Button : "res/button_ok.png",
    Build_Ng_Button : "res/button_ng.png",

    Button_Attack_png : "res/button_attack.png",
    Button_Attack_On_png : "res/button_attack_on.png",
    Button_Add_People_png : "res/button_add_people.png",
    Button_Add_People_On_png : "res/button_add_people_on.png",
    Button_Destroy_png : "res/button_destroy.png",
    Button_Destroy_On_png : "res/button_destroy_on.png",
    Button_Action_Disable_png : "res/button_action_disable.png",

    Building_Button_png : "res/button_building.png",
    Building_Button_On_png : "res/button_building_on.png",
    Setting_Button_png : "res/button_setting.png",
    Setting_Button_On_png : "res/button_setting_on.png",
    Info_Button_png : "res/button_info.png",
    Info_Button_On_png : "res/button_info_on.png",
    Button_Credit_png : "res/button_credit.png",
    Button_Close_png : "res/button_close.png",
    Population_Button_png : "res/button_population.png",
    Population_Button_On_png : "res/button_population_on.png",
    Info_Ok_Button_png : "res/button_ok_review.png",
    Info_Ok_Button_On_png : "res/button_ok_review_on.png",
    Button_Sound_On_png : "res/button_sound_on.png",
    Button_Sound_Off_png : "res/button_sound_off.png",
    Tutorial_Left_Button : "res/button_tutorial_left.png",
    Tutorial_Right_Button : "res/button_tutorial_right.png",
    Tutorial_Close_Button : "res/button_tutorial_close.png",

    Effect_Enemy_png : "res/flame3.png",
    Effect_Enemy2_png: "res/pipo-btleffect072.png",
    Effect_Money_png : "res/pipo-btleffect142.png",
    Effect_Hart_png : "res/pipo-btleffect019.png",

    Window_Reset_png : "res/window_reset.png",
    Window_Message_png : "res/window_message_board.png",
    Window_Setting_png : "res/window_shop.png",
    Window_Setting_Menu_png : "res/window_setting.png",
    Message_png : "res/window_message.png",
    Window_Positioning_png : "res/window_positioning.png",
    Window_Description_png : "res/window_description.png",
    Window_Description_Food_png : "res/window_description_food.png",
    Window_Description_Amount_png : "res/window_description_amount.png",
    Window_Description_Safe_png : "res/window_description_safe.png",

    BGM_001_mp3 : "res/bgm_normal.mp3",
    SE_001_mp3 : "res/se_001.mp3",
    SE_002_mp3 : "res/se_002.mp3",
    SE_003_mp3 : "res/se_maoudamashii_system14.mp3",
    SE_004_mp3 : "res/se_maoudamashii_se_sound13.mp3",
    SE_005_mp3 : "res/se_maoudamashii_se_sound15.mp3",
    Himiko_Message_png : "res/window_himiko_msg.png",
    Himiko_png : "res/himiko.png",
    Food_Base_Sprite_png : "res/f_i001_base.png",
    Himiko_png : "res/himiko_big.png",
    Credit_png : "res/credit.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}